plugins:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate-v2

exclude:
  - "/vendor/"

# Site settings
title: Voisins Vigilants et Solidaires
subtitle: Le blog officiel
email: support@voisinsvigilants.org
name: Voisins Vigilants et Solidaires

baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
cover: "/assets/header_voisinsvigilantsorg.jpg"
logo: "/assets/logoBlog.png"
iconevvs: "/assets/oeil.png"

markdown: kramdown
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"
remote_theme: bencentra/centrarium 

# PAGINATION GITHUB-PAGE
paginate: 5
paginate_path: "blog/page:num"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
#jekyll-archives:
#  enabled:
#    - categories
#    - tags
#  layout: 'archive'
#  permalinks:
#    category: '/category/:name/'
#    tag: '/tag/:name/'
    
collections:
  category:
    output: true # générer la page HTML
    permalink: /:collection/:name/index.html
  tags:
    output: true
    permalink: /tag/:name/

defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: "posts_by_category"
  - scope:
      path: ""
      type: tags
    values:
      layout: "archive"

protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/bencentra/centrarium.com"
    os_rcs_type: "git"
    os_src: "git@github.com:bencentra/centrarium.com.git"
