# External plugins
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
plugins:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate-v2

exclude:
  - "/vendor/"

# Site settings
title: Voisins Vigilants et Solidaires
subtitle: Le blog officiel
email: support@voisinsvigilants.org
name: Voisins Vigilants et Solidaires

# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
cover: "/assets/header_voisinsvigilantsorg.jpg"
logo: "/assets/logoBlog.png"
iconevvs: "/assets/oeil.png"

# Build settings
markdown: kramdown
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"
#theme: jekyll-theme-cayman
remote_theme: bencentra/centrarium 
# Pagination Settings V2
# https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
#pagination:
#  enabled: true
#  per_page: 5
#  permalink: "/page/:num/"
#  sort_reverse: true

# PAGINATION GITHUB-PAGE
paginate: 5
paginate_path: "blog/page:num"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'
    
collections:
  category:
    output: true # générer la page HTML
    permalink: /:collection/:name/index.html

protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/bencentra/centrarium.com"
    os_rcs_type: "git"
    os_src: "git@github.com:bencentra/centrarium.com.git"
