plugins:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate-v2

exclude:
  - "/vendor/"

# Site settings
title: Le blog  de la solidarité <br>et de la vigilance de voisinage
#subtitle: Le blog officiel
email: support@voisinsvigilants.org
name: Voisins Vigilants et Solidaires

baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
cover: "/assets/header_voisinsvigilantsorg.jpg"
logo: "/assets/logo_VVS_carre_150.png"
iconevvs: "/assets/oeil.png"

markdown: kramdown
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"
remote_theme: bencentra/centrarium 

# PAGINATION GITHUB-PAGE
paginate: 5
paginate_path: "blog/page:num"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
#jekyll-archives:
#  enabled:
#    - categories
#    - tags
#  layout: 'archive'
#  permalinks:
#    category: '/category/:name/'
#    tag: '/tag/:name/'
    
collections:
  category:
    output: true # générer la page HTML
    permalink: /:collection/:name/index.html
  tag:
    output: true
    permalink: /tag/:name/

defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: "posts_by_category"
  - scope:
      path: ""
      type: tag
    values:
      layout: "archive"
